import { Box } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Map } from '../components/Map';
import { TitleBar } from '../components/TitleBar';

const Home: NextPage = () => {
  return (
    <div style={{ height: '100vh' }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          height: '100%',
          width: '100%',
          display: 'flex',
          flexDirection: 'column',
        }}
      >
        <TitleBar />
        <Box sx={{ flex: '1 1' }}>input</Box>
        <Box
          sx={{
            flex: '4 4',
            height: '80%',
            width: '100%',
            display: 'flex',
            flexDirection: 'row',
          }}
        >
          <Map />
          <Box sx={{ flex: '1 1' }}>Data</Box>
        </Box>
      </Box>
    </div>
  );
};

export default Home;
